/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciosPDF;

//import EJERCICIOS_CLASES.lineas;
//import JAVA_PRIMER_LIBRO.*;
//import JAVA_PRIMER_LIBRO.Ventana;
//import JAVA_PRIMER_LIBRO.Ventana_Clipping_Path;
//import JAVA_SEGUNDO_LIBRO.*;
//import JAVA_TERCER_LIBRO.*;
import ejerciciosPDF.PrimerLibro.*;
import ejerciciosPDF.SegundoLibro.*;
import ejerciciosPDF.TercerLibro.*;
import ejerciciosPDF.ejerciciosClase.*;

import javax.swing.ComboBoxModel;
import javax.swing.JFrame;
import ordinariomodelado.menuPrincipal;
import parcial3.dibujoCasa;

/**
 *
 * @author omarc
 */
public class menuEjercicios extends javax.swing.JFrame {

    /**
     * Creates new form menuEjercicios
     */
    public menuEjercicios() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBox3 = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jPanel1.setBackground(new java.awt.Color(1, 46, 46));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ejercicios PDF");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ejercicios en Clase");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Primer Libro");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Segundo Libro");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tercer Libro");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuadrado NxN", "Lineas" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ventana", "V. Clipping", "V. Colores", "V. Escala", "V. Grosor", "V. Grosor2", "V. Punteados", "V. Rotación", "V. Shear", "V. Blanca", "V. Gradiente", " V. Textura"}));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arc2DV", "Bañera", "CurvaCuadratica", "Elipse", "Grafica", "Intersecciones", "LineaEstilos", "Rectangulo", "Round Rectangle", "Sherezade", "linea" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DrawArcs", "DrawPolygons", "Fonts", "LinesRectsOvals", "Shapes", "Shapes2", "ShowColors", "ShowColors2" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Menú");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Ejercicio Cuadros");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4)
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(261, 261, 261))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //String itemSeleccionado = jComboBox1.getSelectedItem().toString();
        //EJERCICIOS EN CLASE
        switch(jComboBox1.getSelectedIndex()){
            case 0:
                CuadradoNxN cn = new CuadradoNxN();
                cn.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                cn.setLocationRelativeTo(null);
                cn.setVisible(true);
            break;
            case 1: 
                lineas l = new lineas();
                l.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                l.setLocationRelativeTo(null);
                l.setVisible(true);
        }        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //BOTON DE MENU
        menuPrincipal mp = new menuPrincipal();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        //SEGUNDO LIBRO
        switch(jComboBox3.getSelectedIndex()) {
            case 0:
                Arc2DV arc = new Arc2DV();
                arc.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                arc.setLocationRelativeTo(null);
                arc.setVisible(true);
                break;
            case 1:
                Bañera b = new Bañera();
                b.setDefaultCloseOperation(HIDE_ON_CLOSE);
                b.setLocationRelativeTo(null);
                b.setVisible(true);
                break;
            case 2:
                Curva_Cuadratica cc = new Curva_Cuadratica();
                cc.setDefaultCloseOperation(HIDE_ON_CLOSE);
                cc.setLocationRelativeTo(null);
                cc.setVisible(true);
                break;
            case 3:
                Elipse e = new Elipse();
                e.setDefaultCloseOperation(HIDE_ON_CLOSE);
                e.setLocationRelativeTo(null);
                e.setVisible(true);
                break;
            case 4:
                Grafica g = new Grafica();
                g.setDefaultCloseOperation(HIDE_ON_CLOSE);
                g.setLocationRelativeTo(null);
                g.setVisible(true);
                break;
            case 5:
                Intersecciones i = new Intersecciones();
                i.setDefaultCloseOperation(HIDE_ON_CLOSE);
                i.setLocationRelativeTo(null);
                i.setVisible(true);
                break;
            case 6:
                LineaEstilos le = new LineaEstilos();
                le.setDefaultCloseOperation(HIDE_ON_CLOSE);
                le.setLocationRelativeTo(null);
                le.setVisible(true);
                break;
            case 7:
                Rectangulo rec = new Rectangulo();
                rec.setDefaultCloseOperation(HIDE_ON_CLOSE);
                rec.setLocationRelativeTo(null);
                rec.setVisible(true);
                break;
            case 8:
                RoundRectangle rr = new RoundRectangle();
                rr.setDefaultCloseOperation(HIDE_ON_CLOSE);
                rr.setLocationRelativeTo(null);
                rr.setVisible(true);
                break;
            case 9:
                Sherezade sh = new Sherezade();
                sh.setDefaultCloseOperation(HIDE_ON_CLOSE);
                sh.setLocationRelativeTo(null);
                sh.setVisible(true);
                break;
            case 10:
                linea L = new linea();
                L.setDefaultCloseOperation(HIDE_ON_CLOSE);
                L.setLocationRelativeTo(null);
                L.setVisible(true);
                break;
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        //PRIMER LIBRO
        switch(jComboBox2.getSelectedIndex()) {
            case 0:
                Ventana v = new Ventana();
                v.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                v.setLocationRelativeTo(null);
                v.setVisible(true);
                break;
            case 1:
                Ventana_Clipping_Path vc = new Ventana_Clipping_Path();
                vc.setDefaultCloseOperation(HIDE_ON_CLOSE);
                vc.setLocationRelativeTo(null);
                vc.setVisible(true);
                break;
            case 2:
                Ventana_Colores colores = new Ventana_Colores();
                colores.setDefaultCloseOperation(HIDE_ON_CLOSE);
                colores.setLocationRelativeTo(null);
                colores.setVisible(true);
                break;
            case 3:
                Ventana_Escala ve = new Ventana_Escala();
                ve.setDefaultCloseOperation(HIDE_ON_CLOSE);
                ve.setLocationRelativeTo(null);
                ve.setVisible(true);
                break;
            case 4:
                Ventana_Grosor vg = new Ventana_Grosor();
                vg.setDefaultCloseOperation(HIDE_ON_CLOSE);
                vg.setLocationRelativeTo(null);
                vg.setVisible(true);
                break;
            case 5:
                Ventana_GrosorNegro vgn = new Ventana_GrosorNegro();
                vgn.setDefaultCloseOperation(HIDE_ON_CLOSE);
                vgn.setLocationRelativeTo(null);
                vgn.setVisible(true);
                break;
            case 6:
                Ventana_Punteados vp = new Ventana_Punteados();
                vp.setDefaultCloseOperation(HIDE_ON_CLOSE);
                vp.setLocationRelativeTo(null);
                vp.setVisible(true);
                break;
            case 7:
                Ventana_Rotacion vr = new Ventana_Rotacion();
                vr.setDefaultCloseOperation(HIDE_ON_CLOSE);
                vr.setLocationRelativeTo(null);
                vr.setVisible(true);
                break;
            case 8:
                Ventana_Shear vs = new Ventana_Shear();
                vs.setDefaultCloseOperation(HIDE_ON_CLOSE);
                vs.setLocationRelativeTo(null);
                vs.setVisible(true);
                break;
            case 9:
                Ventana_blanca vb = new Ventana_blanca();
                vb.setDefaultCloseOperation(HIDE_ON_CLOSE);
                vb.setLocationRelativeTo(null);
                vb.setVisible(true);
                break;
            case 10:
                Ventana_gradiente vg1 = new Ventana_gradiente();
                vg1.setDefaultCloseOperation(HIDE_ON_CLOSE);
                vg1.setLocationRelativeTo(null);
                vg1.setVisible(true);
                break;
            case 11:
                Ventana_textura vt = new Ventana_textura();
                vt.setDefaultCloseOperation(HIDE_ON_CLOSE);
                vt.setLocationRelativeTo(null);
                vt.setVisible(true);
                break;
                
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        //TERCER LIBRO
        switch(jComboBox4.getSelectedIndex()) {
            case 0:
                DrawArcs da = new DrawArcs();                
                da.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                da.setLocationRelativeTo(null);
                da.setVisible(true);
                break;
            case 1:
                DrawPolygons dp = new DrawPolygons();
                dp.setDefaultCloseOperation(HIDE_ON_CLOSE);
                dp.setLocationRelativeTo(null);
                dp.setVisible(true);
                break;
            case 2:
                Fonts f = new Fonts();
                f.setDefaultCloseOperation(HIDE_ON_CLOSE);
                f.setLocationRelativeTo(null);
                f.setVisible(true);
                break;
            case 3:
                LinesRectsOvals lro = new LinesRectsOvals();
                lro.setDefaultCloseOperation(HIDE_ON_CLOSE);
                lro.setLocationRelativeTo(null);
                lro.setVisible(true);
                break;
            case 4:
                Shapes sh = new Shapes();
                sh.setDefaultCloseOperation(HIDE_ON_CLOSE);
                sh.setLocationRelativeTo(null);
                sh.setVisible(true);
                break;
            case 5:
                Shapes2 s2 = new Shapes2();
                s2.setDefaultCloseOperation(HIDE_ON_CLOSE);
                s2.setLocationRelativeTo(null);
                s2.setVisible(true);
                break;
            case 6:
                ShowColors sc = new ShowColors();
                sc.setDefaultCloseOperation(HIDE_ON_CLOSE);
                sc.setLocationRelativeTo(null);
                sc.setVisible(true);
                break;
            case 7:
                ShowColors2 sc2 = new ShowColors2();
                sc2.setDefaultCloseOperation(HIDE_ON_CLOSE);
                sc2.setLocationRelativeTo(null);
                sc2.setVisible(true);
                break;                           
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //EJERCICIO DE LOS CUADROS
        
        frameControlesMejorado fc = new frameControlesMejorado();
        fc.setDefaultCloseOperation(HIDE_ON_CLOSE);
        fc.setLocationRelativeTo(null);
        fc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuEjercicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
